baseURL = "https://shark-asmx.github.io/"
languageCode = "en-us"
title = "shark-asmx"
theme = "hugo.386"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts" ]
pagination.pagerSize = 20


[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

# [[languages.en.menu.main]]
# name = "posts"
# url = "/posts"
# weight = 20

  [languages.en.params]
  languageAltTitle = "English"
    [languages.en.params.logo]
    logoText = "shark.exe [0]"
    logoHomeLink = "/posts"

    [languages.en.params.profileMode]
    enabled = true
    title = "shark-asmx"
    imageUrl = "https://avatars.githubusercontent.com/u/89577007"
    imageTitle = "Profile image"
    imageWidth = 130
    imageHeight = 130
    subtitle = " ~/"

      [[languages.en.params.profileMode.buttons]]
      name = "Blog"
      url = "posts"

[params]
env = "production"
mainpagetitle = "hex codes"
mainpagesubtitle = "shark blog"
copyrightname = "shark-asmx"
mainpagedesc = '''
    ```tiny jar on my shelf, collecting strange ideas and random thoughts at /posts```
'''
loadspeedfactor = 10.0
description = "shark-asmx's blog"
author = "shark-asmx"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
theme = "dark"
palette = "hugo.386"
showThemeNotice = true
showPostsSummary = true
contentTypeName = "posts"
themeColor = "orange"
fullWidthTheme = false

  [params.profileMode]
  enabled = false
  title = "shark-asmx"
  imageUrl = "#"
  imageTitle = "my image"

    # [[params.profileMode.buttons]]
    # name = "Tags"
    # url = "tags"

  [params.homeInfoParams]
  Title = "Hii, I'm shark-asmx."
  Content = [
  "I'm Sabhya Raj Mehta currently pursuing B.Tech CSE in Amrita Vishwa Vidhyapeetham. I'm DFIR enthusiast, playing CTFs with teambi0s & DFIR category lead @ bi0s."
]

  [[params.socialIcons]]
  name = "Github"
  title = "Join me on Github"
  url = "https://github.com/shark-asmx"

  [[params.socialIcons]]
  name = "X"
  title = "Join me on Twitter"
  url = "https://twitter.com/shark-asmx"

  [[params.socialIcons]]
  name = "linkedin"
  title = "Join me on LinkedIn"
  url = "https://www.linkedin.com/in/sabhya05/"


  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true



[menu]
  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/posts/"       # The path can lead to a content folder too.
    weight = 20

    [[menu.main]]
    name = "posts"
    url = "/posts"
    weight = 20
